# Configuration for Gitlab-CI.
# Builds appear on https://gitlab.com/essensium-mind/buildroot-relayr/pipelines

image: buildroot/base:20180318.1724

.project: &project
    cache:
        key: buildroot-cache
        paths:
            - dl/
    artifacts:
        when: always
        expire_in: 2 weeks
        paths:
            - project1_x86_64.log
            - o-${CI_JOB_NAME}/images/
            - o-${CI_JOB_NAME}/build/build-time.log
            - o-${CI_JOB_NAME}/build/packages-file-list.txt
    script:
        - ./makebr --brief world
        - ./makebr --brief legal-info

project1_x86_64: *project
