#!/bin/bash
# Made by David De Grave, 2017
# david.degrave@mind.be

# CONFIG
BOARD="x86_64"
SUFFIX="master"

BUILDROOT_REPO="git://git.buildroot.net/buildroot.git"
BUILDROOT_BRANCH="master"
BUILDROOT_TAG=""
###

BASE_DIR=$(readlink -f "$0")
BASE_DIR=${BASE_DIR%/*}
CONFIG_DIR="${BASE_DIR}/configs"
PROJECT=$(sed -n 's/^name: \(.*\)/\1/p' < "$BASE_DIR/project/external.desc")
BUILD=${BOARD}
DEFCONFIG="${BOARD}_defconfig"
EXTERNAL="../project"
OUTPUT="${BASE_DIR}/o-${BUILD}"

# Space separated list of tools required for the build
# (Basically the non common tools used in all the scripts)
HOSTDEPTOOLS=(git awk make)

. scripts/include/log || exit 1

extra=
overrides=
build=normal
make=make

while [ "${1:0:2}" == '--' ]; do
	case $1 in
	 --j)           extra+=" BR2_JLEVEL=$2"; shift;;
	 --configure)	configure=1;;
	 --rebuild)	rebuild=1;;
	 --reinstall)	reinstall=1;;
	 --low)		make="nice -n 5 -- $make";;
	 --debug)	debug=1;;
	 --brief)	build=brief;;
	 --init)	init=1;;
	 *)
		echo "--init      Just download/update external objects"
		echo "--configure Just init and configure buildroot"
	 	echo "--rebuild   Restart the build from scratch"
		echo "--reinstall Force the reinstall of target without a full rebuild"
	 	echo "--debug     Create a debug build"
	 	echo "--brief     Create a log file and show lesser outputs"
		echo "--low       Start building with a lower ressources priority"
		echo "--j <n>     Use max <n> cpus"
	 	exit;;
	esac
	shift
done

for tool in ${HOSTDEPTOOLS[*]}; do
	command -v $tool &>/dev/null || \
	  die "The tool '${C_LCY}${tool}${C_NRM}' is missing and required ! Please install it before continuing ..."
done

init_br() {
	# $1 = directory name, e.g. buildroot
	# $2 = remote repository, e.g. $BUILDROOT_REPO
	# $3 = branch name, e.g. $BUILDROOT_BRANCH
	# $4 = optional tag name to stick to, e.g. $BUILDROOT_TAG

	if [ ! -d "$1" ]; then
		log "Retrieving buildroot from upstream ..."

		if ! git ls-remote --heads "$2" "$3" > /dev/null; then
			echo
			echo "There was a problem retrieving buildroot..."
			echo
			echo "Make sure that:"
			echo "  1. The repository is the right one: $2"
			echo "  2. Your ssh key is registered at the remote."
			echo "  3. You have (read) access to this repository."
			echo "  4. The branch '$3' exists."
			[ $4 ] && \
			echo "  5. The tag '$4' exists."
			exit 1
		fi
		log "Cloning buildroot from $2 ..."
		git clone "$2" "$1" || die "Exit code $?"
	fi
	local checkout=${4:-$3}
	log "Checking out '$checkout'"
	git -C "$1" checkout "$checkout" 2>&1 | grep "^\(HEAD\|Your branch is\)" || dierc $? "Exit code $?"
}

init_br buildroot "$BUILDROOT_REPO" "$BUILDROOT_BRANCH" "$BUILDROOT_TAG"

if [ $init ]; then
	log "init done!"
	exit 0
fi

[ -f "${CONFIG_DIR}/$DEFCONFIG" ] || dierc 2 "defconfig '$DEFCONFIG' not found !"

if   [ $rebuild ]; then
	read -p "Sure to cleanup everything ?!! (CTRL-C to abord)"
	[ -e "$OUTPUT/debug_build" ] && mv "$OUTPUT/debug_build" /tmp/~debug_build.$$
	t="$OUTPUT.$$"
	mv "$OUTPUT" "$t" 2>/dev/null && { rm -rf "$t" & }
elif [ $reinstall ]; then
	find $OUTPUT/build -regex '.*\.stamp_.*\(built\|installed\)' -delete
	rm -rf $OUTPUT/{final,staging} $OUTPUT/{host,images,target}/*
fi

brief() {
	local ret start d h m mf sf line

	start=${SECONDS}

	$make -C buildroot "O=$OUTPUT" $extra "${@}" 2>&1 | {
		while read line; do
			printf "%(%H:%M:%S)T %s\n" -1 "${line}"
		done \
		| tee -a "$OUTPUT/build.log" \
		| grep --line-buffered --colour=never -E '>>>'
	}
	ret=${PIPESTATUS[0]}

	d=$((SECONDS-start))
	printf "Done in "
	h=$((d/3600))
	d=$((d%3600))
	[ $h -ne 0 ] && { printf "%dh " $h; mf="02"; }
	m=$((d/60))
	d=$((d%60))
	[ $m -ne 0 ] && { printf "%${mf}dmin " $m; sf="02"; }
	printf "%${sf}ds\n" $d

	return $ret
}

normal() {
	$make -C buildroot "O=$OUTPUT" $extra "$@"
}

if [ ! -e "$OUTPUT" ]; then
	mv /tmp/~debug_build.$$ "$OUTPUT/debug_build" 2>/dev/null
	if [ $debug ]; then
		[ -e "$OUTPUT/debug_build" ] || cp -a configs/debug_build "$OUTPUT"
		${EDITOR:-vi} "$OUTPUT/debug_build"
		touch "$OUTPUT/debug_build"
	fi
	log "Configuring buildroot ..."
	overrides+=" BR2_EXTERNAL=$EXTERNAL"
	overrides+=" BR2_DEFCONFIG=$CONFIG_DIR/$DEFCONFIG"
	$build defconfig $overrides || dierc $? "Error code $?"
	# Patching the config
	mv -f "$OUTPUT/.config" "$OUTPUT/.config.old"
	awk < "$OUTPUT/.config.old" > "$OUTPUT/.config" -f <(cat <<-EOT
		BEGIN{
		    FS="="
		    addafter["BR2_ROOTFS_POST_BUILD_SCRIPT"] = "../boards/${BOARD}/post-build-hook ../project/post-build-hook"
		    addafter["BR2_ROOTFS_POST_IMAGE_SCRIPT"] = "../boards/${BOARD}/post-image-hook ../project/post-image-hook"
		    addafter["BR2_ROOTFS_OVERLAY"] = "../boards/${BOARD}/fs-overlay ../project/fs-overlay"
		    replace["BR2_DL_DIR"] = "../dl"
		}{
		    if (\$1 in addafter) {
		        if (index(\$0, addafter[\$1])) {
		            print
		        } else {
		            gsub(/"/,"")
		            printf "%s=\\"%s %s\\"\\n",\$1,\$2,addafter[\$1]
		        }
		        delete addafter[\$1]
		    } else if (\$1 in replace) {
		        printf "%s=\\"%s\\"\\n",\$1,replace[\$1]
		        delete replace[\$1]
		    } else {
		        print
		    }
		}
		END{
		    for(f in addafter){
		        printf "%s=\"%s\"\n",f,addafter[f]
		    }
		    for(f in replace){
		        printf "%s=\"%s\"\n",f,replace[f]
		    }
		}
	EOT
	)
	log "Downloading/checking all the source packages ..."
	$build source || dierc $? "Error code $?"
fi

if [ $configure ]; then
	log "Configure done!"
	exit 0
fi

log "Start building $(date)"
$build "${@}" || dierc $? "Error code $?"
log "Build well done $(date)"
