#!/bin/bash

MAINDIR=$(sed -n 's/BR2_DEFCONFIG="\(.*_defconfig\)"/\1/ p' < "$BR2_CONFIG")
MAINDIR=$(readlink -f "${MAINDIR%/*}/..")
SCRNAME=$(readlink -f "$0")
SCRNAME=${SCRNAME#$MAINDIR/}

. "$MAINDIR"/scripts/include/log || exit 1

logTitle "Running $SCRNAME ..."

. "$MAINDIR"/projects/common/post-image-hook || exit $?

# CODE HERE

logTitle "$SCRNAME done!"
exit 0
